# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  manuphatak.com:
    site_hosts:
      - manuphatak.com
    www_redirect: true
    local_path: /Code/manuphatak.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    repo: https://github.com/bionikspoon/manuphatak.com
    branch: master
